Add AverageRSSI, BandwidthTest, SimpleRx & Beacon tools
monash-human-power/ZetaRFTools pull request #1
Opened 2020-07-20 12:11 UTC by hallgchris

## Description

This PR adds four tools for testing and experimenting with the radio module. From the readme:

Name          | Description
--------------|-------------
`AverageRSSI`   | Listens for any and all packets, and measures the Received signal strength indication (RSSI) of each. You can set the duration the test runs for, and the expected number of packets for calculating drop percentages.
`BandwidthTest` | Tries to send a specified number of packets of a specified size as quickly as possible, and measures the speed that it does so.
`SimpleRx`      | Prints all received messages as text and hex, as well as their RSSI.
`Beacon`        | Sends a packet repeatedly at a given interval

This PR also contains two radio configurations not contained in the ZetaRF library. They are 433 MHz fixed-packet configs that are identical to the one contained in ZetaRF, except with higher theoretical bandwidths of 20 kbps and 128 kbps. The default config has a theoretical bandwidth of 2.4 kbps. In practice I am able to achieve speeds of around 7.7 kbps, 39 kbps and 0.95 kbps respectively. I think the 20 kbps config should be sufficient for our purposes at MHP, but I also have not yet found any disadvantage of going higher. (perhaps reliability may be an issue?)

## Screenshots

### Compilation from scratch

![image](https://user-images.githubusercontent.com/17876556/87934213-f70cac80-cad1-11ea-8a53-85912e807613.png)

### Running `BandwidthTest`

![image](https://user-images.githubusercontent.com/17876556/87934485-7ef2b680-cad2-11ea-994f-214e65ec471b.png)

### Resultant output from `SimpleRx` running on a second Pi

Ignore the jank, random bytes aren't great ascii... Note the hex is the same as above

![image](https://user-images.githubusercontent.com/17876556/87935490-903cc280-cad4-11ea-9666-2f2bc12ba561.png)

### Running `Beacon`

![image](https://user-images.githubusercontent.com/17876556/87935841-2d97f680-cad5-11ea-9477-09872044d5a6.png)

### Running `AverageRSSI` to measure the signal strength from `Beacon`

(Again, running on a separate Pi)

![image](https://user-images.githubusercontent.com/17876556/87935882-3ee10300-cad5-11ea-9bb1-96450f20dfb8.png)

## Steps to Test

If you have a raspberry pi handy, you can try compiling following the instructions in the readme. If you somehow have a Zeta module too, you'll need to wire it up as specified in the `ZetaRfConfig` type inside the `ZetaTestBase` class (`ZetaTest.hpp`)

2020-07-21 09:02 UTC, khanguslee requested changes
I obviously can't test this myself, so I'll trust you that it works. Here are some things that I would like additionally:
- Can you create a `.gitignore` folder and add `/CMakeFiles` directory and other CMake related files?
- Add some documentation into your classes. Preferably should conform to doxygen format: https://www.doxygen.nl/index.html

If we wanted to make this more 'complete', some CLI arguments passed into each script would be awesome. But this can be done another time!

2020-07-21 09:02 UTC, khanguslee commented on README.md
> +Clone the repository and initialise submodules with `git clone <url> --recurse-submodules`. If you've already cloned, run `git submodule update --init` to set up the submodules.
I think this would be easier to read if it was more like the following format:

1. Clone the repository and initialise submodules 
   ```
    git clone <url> --recurse-submodules
   ```

2. set up the submodules

   ```
   git submodule update --init
   ```
etc.

2020-07-21 09:02 UTC, khanguslee commented on src/AverageRSSI.cpp
> +    void measureRssi(int testDuration, int expectedPackets=-1)
This was something I learnt years ago, but you should actually always put `const` into your parameters if you also intend the input data to NOT be altered with. You might want to do that with all your methods.

https://isocpp.org/wiki/faq/const-correctness#overview-const

2020-07-21 09:02 UTC, khanguslee commented on src/BandwidthTest.cpp
> +    void measureBandwidth(int packets)
const correctness here as above

2020-07-21 09:02 UTC, khanguslee commented on src/Beacon.cpp
> +    void begin(std::chrono::milliseconds interval)
const correctness as above

2020-07-21 09:02 UTC, khanguslee commented on src/ZetaTest.hpp
> +    ZetaTestBase(size_t packetLength)
const correctness as above

2020-07-21 09:02 UTC, khanguslee commented on src/ZetaTest.hpp
> +    std::vector<uint8_t> generateRandomPacket(size_t size)
const correctness as above

2020-07-21 09:42 UTC, hallgchris commented on src/AverageRSSI.cpp
> +    void measureRssi(int testDuration, int expectedPackets=-1)
Forgot about this, too much python lol

2020-07-22 07:59 UTC, khanguslee commented on src/ZetaTest.hpp
> +     * https://xkcd.com/221/
🤣

2020-07-22 07:59 UTC, khanguslee approved these changes
LGTM!

2020-07-24 03:52 UTC, merged